version: "3.8"
services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  app:
    build: .
    restart: always
    env_file: .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/kaiser
      - NODE_ENV=production
    depends_on:
      - mongo
    ports:
      - "4000:4000"

volumes:
  mongo-data:
